-- Create the Activity Logs table
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_email TEXT NOT NULL,
    action TEXT NOT NULL, -- e.g., 'LOGIN', 'VIEW_LESSON', 'START_QUIZ'
    details JSONB, -- Flexible JSON for extra info (e.g., {"day": 5, "score": 10})
    user_agent TEXT -- Optional: Browser/Device info
);

-- Enable RLS (Row Level Security)
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Policy 1: Students can INSERT their own logs (implicitly, or open to auth users)
CREATE POLICY "Enable insert for authenticated users" ON activity_logs
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Policy 2: Only Admins (Service Role) can VIEW all logs
-- Note: In our app, the Admin Dashboard uses the Service Key, so it bypasses RLS.
-- But if you log in as a user, you shouldn't see others' logs.
CREATE POLICY "Enable read for service role only" ON activity_logs
    FOR SELECT USING (auth.role() = 'service_role');

-- Optional: Create an index for faster filtering by action or user
CREATE INDEX IF NOT EXISTS idx_activity_logs_action ON activity_logs(action);
CREATE INDEX IF NOT EXISTS idx_activity_logs_email ON activity_logs(user_email);
