-- Feed Nuggets V2 (Topic-Centric)
-- Dropping old table to rebuild schema
DROP TABLE IF EXISTS feed_nuggets;

CREATE TABLE feed_nuggets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    lesson_day INTEGER NOT NULL,
    topic TEXT NOT NULL,  -- e.g. "Variables", "Conditionals"
    title TEXT NOT NULL,  -- Punchy headline
    
    -- Type: 'tip', 'mnemonic', 'snippet', 'image'
    type TEXT NOT NULL,
    
    -- The main text content. 
    -- If type='image', this might be the caption or alt text.
    content TEXT,
    
    -- URL for the image (if type='image')
    media_url TEXT,
    
    -- Sorting/Priority
    virality_score INTEGER DEFAULT 5
);

-- Optimize for "Give me all nuggets for Day X"
CREATE INDEX idx_feed_nuggets_day_topic ON feed_nuggets(lesson_day, topic);

-- RLS Policies (Standard)
ALTER TABLE feed_nuggets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON feed_nuggets
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable write access for service role only" ON feed_nuggets
    FOR ALL USING (auth.role() = 'service_role');
