-- Feed Nuggets Table for AI-Refined Content
-- Drop table if exists to allow clean reset during dev
DROP TABLE IF EXISTS feed_nuggets;

CREATE TABLE feed_nuggets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    
    lesson_day INTEGER NOT NULL,
    
    -- Content Type: 'code', 'fact', 'trap', 'analogy'
    type TEXT NOT NULL,
    
    -- Punchy title for the card (e.g. "Traps of Day 1")
    title TEXT NOT NULL,
    
    -- The main content (HTML or Code Snippet)
    content TEXT NOT NULL,
    
    -- Viral Score (1-10) for sorting/priority
    virality_score INTEGER DEFAULT 5,
    
    -- Metadata (e.g. source model used)
    meta JSONB DEFAULT '{}'::jsonb
);

-- Index for fast lookup by day
CREATE INDEX idx_feed_nuggets_day ON feed_nuggets(lesson_day);

-- Enable RLS
ALTER TABLE feed_nuggets ENABLE ROW LEVEL SECURITY;

-- Allow Read Access to All Authenticated Users
CREATE POLICY "Enable read access for all users" ON feed_nuggets
    FOR SELECT USING (auth.role() = 'authenticated');

-- Allow Insert/Update only to Service Role (Admin)
CREATE POLICY "Enable write access for service role only" ON feed_nuggets
    FOR ALL USING (auth.role() = 'service_role');
